name: project-lifecycle
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read

jobs:
  lifecycle:
    uses: ./.github/workflows/wfc_lifecycle.yml
