name: pr-mgmt
on:
  pull_request: {}

jobs:
  pr-mgmt:
    uses: lahabana/kumahq_.github/.github/workflows/wfc_pr_management.yml@main
    with:
      approve: true
      merge: true
      matchTitle: "AUTO MERGE"
      matchLabel: "auto-merge"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
