name: pr-mgmt
on:
  pull_request:
    types: [labeled,opened,reopened,edited,ready_for_review]

jobs:
  pr-mgmt:
    uses: lahabana/kumahq_.github/.github/workflows/wfc_pr_management.yml@main
    with:
      approve: true
      merge: true
      matchLabel: "auto-merge"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
