name: MarkForTriage
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add_triage_label:
    uses: kumahq/.github/.github/workflows/wfc_add_labels.yml@main
    with:
      issue: ${{ github.event.issue.number }}
