on:
  workflow_call:
    inputs:
      matchTitle:
        description: "A regexp to match against the PR title"
        type: string
        required: true
      matchLabel:
        description: "A set of labels to match PR against"
        type: string
      approve:
        description: "Whether the PR should be auto approved"
        default: false
        required: false
      merge:
        description: "Whether the PR should be auto merged"
        default: false
        required: false
      comment:
        description: "Whether we should comment the actions we do"
        type: string
        required: false
    secrets:
      github-token:
        description: 'GitHub Token'
        required: true

jobs:
  open:
    if: github.event.pull_request && (contains(github.event.pull_request.labels.*.name, inputs.matchLabel) || contains(github.event.pull_request.title, inputs.matchTitle))
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.github-token }}
    steps:
      - name: approve
        if: inputs.approve
        run: |
          gh pr review ${{ github.event.pull_request.number }} -a -R ${{ github.repository }} -c "Auto approved by PR action ${{ github.workflow }} ${{ github.action }} ${{ github.run_number }}"
      - name: merge
        if: inputs.merge
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -b "Enabling auto merge ${{ github.workflow }} ${{ github.action }} ${{ github.run_number }}"
          gh pr merge ${{ github.event.pull_request.number }} --auto -R ${{ github.repository }}
      - name: comment
        if: inputs.comment
        run:
          gh pr comment ${{ github.event.pull_request.number }} -R ${{ github.repository }} -c "${{ inputs.comment }}"
